### ISSUE TITLE
FYI: I created project pylkc as an alternative to Kconfiglib

### ISSUE THREAD

**Issue by fpemud** [ulfalizer/Kconfiglib#12]
I have encountered bug again when I use Kconfiglib to operate Linux-3.17, so I create a new project fpemud/pylkc.
pylkc provides the same function as Kconfiglib (with different API) and the implementation is way much simpler and more maintainable by reusing the C code in "LINUX_SRC_DIR/scripts/kconfig". I also expect it to be more accurate and have less bugs for the same reason. pylkc also has its limitations, which is  elaborated in README.
It has not been completed yet, but can already serve my project fpemud-kernelmanger well enough.

**Comment by ulfalizer** [comment]
(Just for the record, Kconfiglib isn't dead. I realized the above might sound overly negative to people checking out the issues. :P)

**Comment by ulfalizer** [comment]
Closing this issue for now, as I think Kconfiglib is very robust again after the `allnoconfig_y` fixes. I added a link to your project to the readme instead.

Bug reports are always welcome.
