### ISSUE TITLE
kconfiglib needs a new maintainer?

### ISSUE THREAD

**Issue by jackrosenthal** [ulfalizer/Kconfiglib#121]
I love kconfiglib, it's a great Python library. But several issues and PRs have been opened in the past 2 years without response from @ulfalizer .

@ulfalizer -- do you intend to continue to maintain this library?

**Comment by gmsotavio** [comment]
I love kconfiglib too, but It seems @ulfalizer is not much active lately.

![image](https://user-images.githubusercontent.com/10669626/193067712-190b4773-4c77-4e28-876a-4aeed29d9bf1.png)
![image](https://user-images.githubusercontent.com/10669626/193067830-17d36ebe-b280-4767-9c37-2b3c99a25da1.png)

**Comment by orzel** [comment]
There are lot of forks. None would volunteer to maintainership ? Alas, most of them are untouched for years, often even more than this one :(

**Comment by jackrosenthal** [comment]
I'll setup a fork and look at

- Integrating the pending PRs.
- Fixing open issues.
- Making a new release.

**Comment by marc-hb** [comment]
@ulfalizer has left the Internet a couple years ago. Thanks @jackrosenthal for volunteering!

**Comment by marc-hb** [comment]
One thing @ulfalizer was proud about is an extensive test-suite making sure `kconfiglib.py` was 99%, bug-for-bug compatible with Linux's kconfig. That test suite (and maybe others) should be in the repo, please make sure you get familiar with it. EDIT: it's mentioned in the README

@mbolivar-nordic any other advice, names of people who could help?

**Comment by stephanosio** [comment]
We could look into forking the Kconfiglib repository under the [GitHub `zephyrproject-rtos` organisation](https://github.com/zephyrproject-rtos/) and give write access to whomever willing to maintain it in order to ensure that the disappearance of single person does not block further development and maintenance of the library in the future.

**Comment by mbolivar-nordic** [comment]
> @mbolivar-nordic any other advice, names of people who could help?

The main person in Zephyr who has taken over Kconfig maintenance is @tejlmand.

> We could look into forking the Kconfiglib repository under the [GitHub zephyrproject-rtos organisation](https://github.com/zephyrproject-rtos/)

One alternative is a new `kconfiglib` organization if enough people are using kconfiglib for things other than zephyr.

**Comment by marc-hb** [comment]
> The main person in Zephyr who has taken over Kconfig maintenance is @tejlmand.

Good to know! So where is the "upstream" repo now?

**Comment by mbolivar-nordic** [comment]
No no no, that's not what I'm saying. I'm saying that **within zephyr**, the person who has been maintaining the library usage is @tejlmand, not that he is the upstream kconfiglib maintainer. There is no such person.

**Comment by carlescufi** [comment]
@jackrosenthal would you be open to having this hosted under the [GitHub zephyrproject-rtos organisation](https://github.com/zephyrproject-rtos/)  with you as a maintainer?

**Comment by jackrosenthal** [comment]
Yes, this sounds great to me!

**Comment by marc-hb** [comment]
Awesome, I will file a new "Add randconfig" feature request to celebrate!

Will this be it? https://github.com/zephyrproject-rtos/Kconfiglib

Childish desire to create the issue number 1 ;-)

**Comment by carlescufi** [comment]
@jackrosenthal the Zephyr TSC has agreed to host this, but there are questions about the name (whether it should be changed). Let's continue the discussion in [Zephyr's Discord](https://chat.zephyrproject.org/) before we close this issue. In particular let's use the `#build-system` channel for this discussion.

**Comment by fschrempf** [comment]
Thanks everyone for caring about continued maintenance of Kconfiglib!

Are there already results out of the discussion about the future place of the repo and name of the project? Maybe someone knows how to reach out to @ulfalizer to get access to the GitHub repo and PyPi entry so they can continued to be used. Otherwise I guess there's no way around a new name to avoid conflicts with the legacy packages!?

**Comment by carlescufi** [comment]
> Thanks everyone for caring about continued maintenance of Kconfiglib!
> 
> Are there already results out of the discussion about the future place of the repo and name of the project? Maybe someone knows how to reach out to @ulfalizer to get access to the GitHub repo and PyPi entry so they can continued to be used. Otherwise I guess there's no way around a new name to avoid conflicts with the legacy packages!?

There is an ongoing discussion about the name and the hosting under the `zephyrproject-rtos` GitHub org. I will submit a proposal to the Zephyr TSC and follow-up here.

EDIT: Regarding contacting Ulf, I've tried that personally over various communication means without success. At this point I believe we will not be able to discuss this with him, so renaming seems like the better option.

**Comment by jackrosenthal** [comment]
I'm going to close this discussion here, as active discussion is now happening in this thread: https://github.com/zephyrproject-rtos/zephyr/issues/53894
