### ISSUE TITLE
Boolean default not taken if written after help

### ISSUE THREAD

**Issue by DonBrus** [ulfalizer/Kconfiglib#124]
Hi,

I recently encountered an error when trying to setup a default value for _boolean_ options, whenever I also include a _help_ instruction within the menu.

### The following works in setting the default value correctly
```kconfig
menu "General options"
	config Kconf_Options_Foo
		bool "This is the foo option"
		default y
endmenu
```
![working-bool-default](https://user-images.githubusercontent.com/8736534/212279946-a818bfe2-8cbf-4699-9840-3bee6f8b8650.png)

### This, in turn, does **not** work:
```kconfig
menu "General options"
	config Kconf_Options_Foo
		bool "This is the foo option"
                help "This setups foo, which causes baz"
		default y
endmenu
```
![non-working-bool-default](https://user-images.githubusercontent.com/8736534/212280093-d5947262-39cf-432f-88b4-b5c74fed2335.png)

### Inverting _default_ and _help_ prevents parsing of KConfig file
```kconfig
menu "General options"
	config Kconf_Options_Foo
		bool "This is the foo option"
                default y
                help "This setups foo, which causes baz"
endmenu
```
produces
> menuconfig.py: error: expected 'endmenu' at end of 'Kconfig'

I'm using the latest pip package (14.1.0).
Is this expected behavior? Am I doing something wrong?

Btw I've seen issue #121 however it's not clear to me whether a takeover is already taking place or not; if so, I'd like to report this issue over to the new repo, if any exist.

Thanks!

**Comment by Honza0297** [comment]
I know this is bit of an archaeology to reply to this, but maybe it will help somebody in the future. :) 
The true issue is that the syntax is incorrect; help text should be at a new line with indentation: 

```
  menu "General options"
      
      config IDF_FOO
          bool "This is the foo option"
          help 
              "Some help text"
          default y

  endmenu
```

**Comment by DonBrus** [comment]
Hey @Honza0297 thanks for the explanation! Incidentally I started using the right syntax months after and forgot about this issue. Much appreciated!
