### ISSUE TITLE
hi first example I tried failed

### ISSUE THREAD

**Issue by narutocanada** [ulfalizer/Kconfiglib#15]
hi
first example I tried failed (Example 5: print a tree of all items in the configuration.)
failed for both linux-3.10.79 and linux-4.0.4

python py/print.config.tree.py /linux-3.10.79/arch/x86/configs/x86_64_defconfig 

/linux-3.10.79/arch/x86/configs/x86_64_defconfig:1:
Traceback (most recent call last):
  File "py/print.config.tree.py", line 20, in <module>
    conf = kconfiglib.Config(sys.argv[1])
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 214, in __init__
    self.top_block = self._parse_file(filename, None, None, None)
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 919, in _parse_file
    return self._parse_block(line_feeder, None, parent, deps, visible_if_deps, res)
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 972, in _parse_block
    tokens = self._tokenize(line, False, filename, linenr)
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 639, in _tokenize
    _tokenization_error(s, len(s), filename, linenr)
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 3782, in _tokenization_error
    " " * vis_index + "^\n"))
kconfiglib.Kconfig_Syntax_Error: Error during tokenization at location indicated by caret.

CONFIG_EXPERIMENTAL=y
                     ^

python py/print.config.tree.py /linux-4.0.4/arch/x86/configs/x86_64_defconfig 

/linux-4.0.4/arch/x86/configs/x86_64_defconfig:1:
Traceback (most recent call last):
  File "py/print.config.tree.py", line 20, in <module>
    conf = kconfiglib.Config(sys.argv[1])
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 214, in __init__
    self.top_block = self._parse_file(filename, None, None, None)
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 919, in _parse_file
    return self._parse_block(line_feeder, None, parent, deps, visible_if_deps, res)
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 972, in _parse_block
    tokens = self._tokenize(line, False, filename, linenr)
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 639, in _tokenize
    _tokenization_error(s, len(s), filename, linenr)
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 3782, in _tokenization_error
    " " * vis_index + "^\n"))
kconfiglib.Kconfig_Syntax_Error: Error during tokenization at location indicated by caret.

CONFIG_EXPERIMENTAL=y
                     ^

**Comment by narutocanada** [comment]
hi
I also tried "make defconfig" first. still error.

cd /linux-4.0.4/ ; make defconfig 
python py/print.config.tree.py /linux-4.0.4/.config # also failed

Traceback (most recent call last):
  File "py/print.config.tree.py", line 20, in <module>
    conf = kconfiglib.Config(sys.argv[1])
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 214, in __init__
    self.top_block = self._parse_file(filename, None, None, None)
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 919, in _parse_file
    return self._parse_block(line_feeder, None, parent, deps, visible_if_deps, res)
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 972, in _parse_block
    tokens = self._tokenize(line, False, filename, linenr)
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 639, in _tokenize
    _tokenization_error(s, len(s), filename, linenr)
  File "/usr/lib/python2.7/site-packages/kconfiglib.py", line 3782, in _tokenization_error
    " " * vis_index + "^\n"))
kconfiglib.Kconfig_Syntax_Error: Error during tokenization at location indicated by caret.

CONFIG_64BIT=y

**Comment by ulfalizer** [comment]
Hello,

You can't run the scripts directly on .config files like that. The scripts expect the argument to be a Kconfig file.

.config files (along with e.g. \*_defconfig files) are particular generated configurations. For example, if you enable support for some particular filesystem and save the configuration, then this setting ends up in the .config file.

Kconfig files on the other hand list the available configuration options and their dependencies. When you run e.g. `make menuconfig`, it's the Kconfig files that let menuconfig know what options are available and how they're related.

The proper way to run the script is to apply the Makefile patch and then do

     $ make scriptconfig SCRIPT=Kconfiglib/examples/print_tree.py

You'll find this particular example in the documentation too, which also explains why it's necessary to through `make`.

Oh, and I just noticed that the Makefile patch doesn't apply with Linus' latest kernel due to a few lines were added to the beginning of scripts/kconfig/Makefile. It should be simple to apply manually though, as it's just a block of text that needs to be inserted near the beginning of scripts/kconfig/Makefile. I'll see if I can make it more robust somehow.

Did that solve your problems?

**Comment by narutocanada** [comment]
hi
it works:
cd /linux-3.10.79/;
git clone git://github.com/ulfalizer/Kconfiglib.git
patch -Np1 -i Kconfiglib/makefile.patch
make scriptconfig SCRIPT=Kconfiglib/examples/print_tree.py
Thanks.

If not too much trouble, can you tell me how to list all symbols that depends on a particular symbol, for example, "ETHERNET". (I only need one level of children). I am looking at "Kconfiglib/examples/print_refs.py" but not sure if this is what I am looking for.

**Comment by ulfalizer** [comment]
*Kconfiglib/examples/print_refs.py* is what you want to look at. To also get symbols from menus and ifs that enclose the symbol (this is probably what you want), make sure to pass **True** for the **refs_from_enclosing** argument to **get_referenced_symbols()**.

Defining exactly what it means to "depend on" a particular symbol gets a bit tricky sometimes, as **depends on**, **if**, **select**, etc., can have complex expressions involving **&&**, **||**, and **!** (**AND**, **OR**, and **NOT**). The above will just check what symbols are "mentioned" in relation to the symbol.

**Comment by narutocanada** [comment]
hi
what i am trying do to is to disable all ethernet driver from "make menuconfig" (after make defconfig), then simply add driver for particular machine. is there a simple way to list only those that will show up in "make menuconfig" ? if too complicated, I will give up for now. I m just trying to save some compile time.

**Comment by ulfalizer** [comment]
I think that might get messy. There's probably lots of stuff that depends on the ETHERNET symbol besides just the NIC drivers.

**Comment by narutocanada** [comment]
but, how does make menuconfig does it? i guess it is too hard...

**Comment by ulfalizer** [comment]
I must've misunderstood. Anything you could do in menuconfig you should be able to script in kconfiglib. What are you doing in menuconfig exactly?

I thought you meant automatically figuring out which things are ethernet drivers and disabling those.

**Comment by narutocanada** [comment]
hi
i just did:
grep refs_from_enclosing Kconfiglib/examples/* # nothing
find . -name Kconfig|xargs grep refs_from_enclosing # nothing
find . -name Kconfig|xargs grep -i enclo # not related to this issue
grep -i enclo Kconfiglib/examples/* # nothing
what do i have to do to find all driver symbols that depends on ethernet (or ethernet menu)?

ok wait...
i just did:
find drivers/net/ethernet/ -name Kconfig|xargs head -n5|egrep "^config"
that gives me something interesting...

**Comment by narutocanada** [comment]
hi
i guess if Kconfiglib can print out "the file path" to which the symbol belongs to, then this job would be easier...

**Comment by ulfalizer** [comment]
Note that there is a lot of documentation (docstrings) besides the examples. The readme goes over how to build the documentation.

**refs_from_enclosing** is a parameter to **get_referenced_symbols()**. It's described in the docs.

Disabling all the stuff in the ETHERNET menu would unfortunately be tricky, because the "menu" is relying on an "implicit menu" feature in menuconfig, where menus are constructed automatically from certain "patterns" of dependencies. If it was a real menu, then menu.get_symbols() could be used for example, but unfortunately that doesn't seem to be the case. :/

**Comment by narutocanada** [comment]
I think the all "source" directives in all the Kconfig's starting from the root kernel src dir would give some sorta of structure... I wonder what this tree compared with "Kconfiglib/examples/print_tree.py" look like...

**Comment by narutocanada** [comment]
i tried to see if Kconfiglib keep track of "source" directives or files loading when building symtree, but I can not seem to get it to work, everything seem to point back to "root" only:
I have modified "print_tree.py" to see if files loading was tracked, but none seems to work...
i have tried: get_srctree(), get_base_dir(), get_config_filename(), get_config_header(), get_kconfig_filename(), etc. they are either None or points back to root. Maybe my python coding sucks...

# Prints a tree of all items in the configuration

import kconfiglib
import sys

def print_with_indent(s, indent):
    print (" " * indent) + s

def print_items(items, indent):
    for item in items:
        if item.is_symbol():
          #if item.get_config().get_srctree()is not None: # tried others as well
          if item.get_config().get_config_header() is not None:
            #print_with_indent("config {0}".format(item.get_name())+" "+item.get_config().get_config_filename(), indent)
            #print_with_indent("config {0}".format(item.get_name())+" "+item.get_config().get_srctree(), indent)
            #print_with_indent("config {0}".format(item.get_name())+" "+item.get_config().get_base_dir(), indent)
            print_with_indent("config {0}".format(item.get_name())+" "+item.get_config().get_config_header(), indent)
          else:
            print_with_indent("config {0}".format(item.get_name()), indent)
        elif item.is_menu():
            print_with_indent('menu "{0}"'.format(item.get_title()), indent)
            print_items(item.get_items(), indent + 2)
        elif item.is_choice():
            print_with_indent('choice', indent)
            print_items(item.get_items(), indent + 2)
        elif item.is_comment():
            print_with_indent('comment "{0}"'.format(item.get_text()), indent)

conf = kconfiglib.Config(sys.argv[1])
print_items(conf.get_top_level_items(), 0)

**Comment by ulfalizer** [comment]
`source` statements aren't tracked in the sense that you can walk up a tree of `source` statements or the like. They act kinda like `#include` in C and C++. The filename and location of each symbol is tracked though, but I'm not sure if that would help.

**Comment by narutocanada** [comment]
ok, got it: item.get_def_locations() 
if i compare the string with "/linux-3.10.79/drivers/net/ethernet/" and if it is under the directory, then i will simply set it to "=n".... I will see how this goes...

**Comment by ulfalizer** [comment]
Yeah, that might work, as long as all the drivers are in there, and there aren't other kinds of symbols besides symbols for specific drivers.

**Comment by narutocanada** [comment]
is there a way to find symbols that require values when doing "make oldconfig"?
(or "make iscriptconfig Kconfiglib/examples/defconfig.py" with Kconfiglib)
i look through the doc a few times, but can not find a condition that triggers it?
this would solve my problem much cleaner (simply assign "=n" is a bit dangerous, but works for ethernet)
i could just do what allnoconfig.py does by assigning get_lower_bound() if the condition or symbols are easily enumerated. Currently this is what works for "ethernet" without coding:

make defconfig ; cp .config ~/1
echo "CONFIG_ETHERNET=n" >> .config
make oldconfig
echo "CONFIG_ETHERNET=y" >> .config
yes "n" | make oldconfig
tkdiff .config ~/1
(visual inspection make sure it works as intended)

**Comment by ulfalizer** [comment]
You could use `get_assignable_values()` (`get_lower/upper_bound()` or `get_visibility()` would work too) to find symbols that can be assigned a user value, and use `get_user_value()` to see if they have already been assigned a value (by checking if it returns `None`).

Assigning values in a .config to symbols that wouldn't show up in `menuconfig` is "safe" insofar as it won't have any effect by the way. The C tools work the same way.

`set_user_value()` works exactly like setting a value for the symbol in a .config file by the way.

**Comment by narutocanada** [comment]
none of your suggestion seems to work. I have modified "allnoconfig.py" to quite a few variantions but none would produce the same result. if you don't mind write out the example code, that would produce the same result as the above?

**Comment by ulfalizer** [comment]
I came up with the following:

    import kconfiglib
    import sys
    
    conf = kconfiglib.Config(sys.argv[1])
    
    conf.load_config("arch/x86/configs/x86_64_defconfig")
    conf["ETHERNET"].set_user_value('n')
    
    # This won't write out lines for things that depend on ETHERNET, since those
    # aren't visible
    conf.write_config(".config")
    # This replaces all the user values with the values from the .config, which
    # does not have values for things that depended on ETHERNET
    conf.load_config(".config")
    
    ## Enable ETHERNET again and check for symbols that do not have a user value and
    ## that we can set to 'n'
    conf["ETHERNET"].set_user_value('y')
    for s in conf:
        if s.get_user_value() is None and 'n' in s.get_assignable_values():
            s.set_user_value('n')
    
    ## Write the final configuration
    conf.write_config(".config")

There's a difference in a few symbols (e.g., `NET_PTP_CLASSIFY`) that I need to track down though. I should be sleeping, so maybe it's something really obvious I'm missing. I'll look at it later. :/

One slightly annoying thing I just noticed is that *scripts/kconfig/Makefile* uses `--defconfig` when calling the C implementation. That overrides the `DEFCONFIG_LIST` in *init/Kconfig*, which is what `get_defconfig_filename()` in Kconfiglib uses. I manually specified the defconfig for the program above, but that isn't ideal.

**Comment by ulfalizer** [comment]
Couldn't fall asleep until I had figured out. No bugs involved, just some pretty subtle stuff related to user values.

To get *exactly* the same result as with your version, you pretty much have to mirror what it does, as follows:

    import kconfiglib
    import sys
    
    conf = kconfiglib.Config(sys.argv[1])
    
    # Mirrors defconfig
    conf.load_config("arch/x86/configs/x86_64_defconfig")
    conf.write_config(".config")
    
    # Mirrors first oldconfig
    conf.load_config(".config")
    conf["ETHERNET"].set_user_value('n')
    conf.write_config(".config")
    
    # Mirrors second oldconfig
    conf.load_config(".config")
    conf["ETHERNET"].set_user_value('y')
    for s in conf:
        if s.get_user_value() is None and 'n' in s.get_assignable_values():
            s.set_user_value('n')
    
    # Write the final configuration
    conf.write_config(".config")

**Comment by narutocanada** [comment]
thanks. you sure are dedicated. it's "Sun 06:14 New York Time".
for posterity, my tcl expect version, not clean as your version (the code will simply wait for input if ran into unknown choices):

make defconfig
echo "CONFIG_ETHERNET=n" >> .config
yes "" | make oldconfig
echo "CONFIG_ETHERNET=y" >> .config
echo '#!/usr/bin/expect
set timeout -1
spawn make oldconfig
while {1} { expect {
"Y/n/?" {send "n\r"}
"N/m/y/?" {send "n\r"}
eof {break}
}}' > /tmp/t.ex
expect /tmp/t.ex

**Comment by ulfalizer** [comment]
You don't want to know what time it is in Sweden...
