### ISSUE TITLE
typo in _FileFeed.peek_next()

### ISSUE THREAD

**Issue by dywisor** [ulfalizer/Kconfiglib#17]
There's a typo in ``_FileFeed.peek_next()`` (line [~~3128~~ 3135](https://github.com/ulfalizer/Kconfiglib/blob/a7e0b22c1251c110a0cc0fd30baaada0731b9856/kconfiglib.py#L3135)), which causes it to raise an Exception when dealing with line continuation -  ``res`` should be ``line``.

Didn't feel like forking and creating a pull-req for this minor change, so here's a [patch at gist.github.com](https://gist.github.com/dywisor/627ad2d9d6de1ab66c43)

**Comment by ulfalizer** [comment]
Thanks for the catch!

Looks like that function is only used while reading the .config header. To be honest, the line joining behavior probably doesn't make sense when reading .config files, so the _FileFeed reuse is a bit dubious.

I'll add your patch and some test cases in a separate commit.

Just of curiosity, did you run into this issue in the wild?

**Comment by dywisor** [comment]
> Just out of curiosity, did you run into this issue in the wild?

Random find, actually; no practical use involved so far.
