### ISSUE TITLE
base_dir doesn't work, os.chdir is still required

### ISSUE THREAD

**Issue by neumond** [ulfalizer/Kconfiglib#20]
```
Traceback (most recent call last):
  File "kc3.py", line 24, in <module>
    conf = Config(base_dir='/usr/src/linux')
  File "/home/neumond/.python/kconfiglib.py", line 218, in __init__
    self.top_block = self._parse_file(filename, None, None, None)
  File "/home/neumond/.python/kconfiglib.py", line 604, in _parse_file
    return self._parse_block(_FileFeed(filename), None, parent, deps,
  File "/home/neumond/.python/kconfiglib.py", line 3111, in __init__
    with open(filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Kconfig'
```

**Comment by ulfalizer** [comment]
`base_dir` is only used for `source` statements within Kconfig files (search for `T_SOURCE` to see where it's used). It's not added as a prefix to the `filename` argument to `Config.__init__()`. I think it's more flexible this way.

**Comment by neumond** [comment]
That's hard to figure out for random person trying to reuse the code. I think it's better to rename ```base_dir``` into at least ```source_base_dir```, otherwise it is confusing. Also I see that I need to supply absolute paths to ```load_config``` and all other functions, so this ```source_base_dir``` is really only about ```source``` directive.

**Comment by ulfalizer** [comment]
Did you notice the documentation for `base_dir`? I don't want my code to be confusing, so maybe I could improve it, but I need to know if it's still confusing together with the documentation.

**Comment by ulfalizer** [comment]
The way I feel, `base_dir` is similar to using `-I` with `gcc` to tell the preprocessor where to look for headers. Just as `-I` won't influence where `gcc` looks for input files that you specify (you usually wouldn't specify a header as an input file, but work with me ;)), `base_dir` won't influence where Kconfiglib looks for the base Kconfig file.

**Comment by neumond** [comment]
Hmm, tbh I've only viewed readme and started from one of examples. Docstring documentation is something that I would read to know how any particular function works. And.. I'm lazy to generate it :) usually generated docs are almost useless when you need tutorial/quickstart level.

Anyway, is there any point to search initial Kconfig in current directory instead base_dir? I mean it could be done less confusing still retaining its flexibility, like this:

```python
Config(base_dir='/usr/src/linux', filename='Kconfig')  # relative path resolves to /usr/src/linux/Kconfig
Config(base_dir='/usr/src/linux')  # reasonable filename default can make it even simpler
Config(base_dir='/usr/src/linux', filename='/home/user/Kconfig')  # absolute path is still possible, including join(abspath(os.curdir), 'Kconfig')
```

In any case I'm glad it is possible to make it work without chdir, you may close the issue if you think that current interface is ok. Thanks for help.

**Comment by ulfalizer** [comment]
I'm not sure if people expect the `filename` to be searched for in `base_dir`, and there's a question of backwards compatibility.

I try to make my documentation easy to read by the way, so give it a shot at least. The docstrings are easy enough to read directly in the code too. :)
