### ISSUE TITLE
make -p instead patching makefile

### ISSUE THREAD

**Issue by neumond** [ulfalizer/Kconfiglib#21]
This should print all env variables from makefile. It will require writing standalone parser for ```LANG= make -p``` output. Don't know how nicely this will work under different make systems though. Possible complexity is in recursive makefile system: every makefile can set its own variables, some investigation needed to know whether this affects result.

**Comment by neumond** [comment]
Another _probably_ possible option is a separate makefile somehow importing the original one.

**Comment by ulfalizer** [comment]
Yeah, I worry that there might be more complex and brittle than the patch. I could be convinced though. :)
