### ISSUE TITLE
Lack of proper menuconfig support

### ISSUE THREAD

**Issue by neumond** [ulfalizer/Kconfiglib#22]
Consider ```File systems / Native language support``` path. Despite it's a symbol it behaves exactly like menu. I still can use ```symbol.dep``` to get all descendants, but there's inconsistency, e.g. ```symbol.get_parent()``` of any child would return "File systems" menu node instead "Native language support". Would be cool to see some class like ```class MenuConfig(Symbol, Menu)```.

**Comment by ulfalizer** [comment]
Yeah, this is a known limitation. See the note that starts with "at least two things make it a bit awkward to replicate a 'menuconfig'-like interface..." in the README. Kconfiglib always models the relations exactly as described in the Kconfig files, so it's consistent in that way. It's just that menuconfig adds some "sugar" on top of that in the form of implicit menus.

I think the proper API would be to either add a flag to `get_parent()` to (possibly) get an "implicit" parent, or to add a separate method. Kconfiglib's API could do with less messiness though...

**Comment by neumond** [comment]
Sorry, may be I'm not that deep in knowing internals, I didn't spend much this with kernel config parsing so far, and may be I'm talking silly things.. but I've meant ```menuconfig``` token. If you look at Kconfig file it looks exactly like ```menu``` token, but with ability to have symbol properties. No implicit magic here.

**Comment by ulfalizer** [comment]
Actually, `menuconfig` works exactly like `config`, only (I think) people use it as a for of documentation to show that there's a bunch of other symbols that depend on the symbol (and so an implicit menu gets created).

If you want to see this for yourself, look at the implementation in [zconf.y](http://lxr.free-electrons.com/source/scripts/kconfig/zconf.y) (the Bison parser definition). You'll notice that the code for `T_CONFIG` is the same as for `T_MENUCONFIG`.

**Comment by neumond** [comment]
I can't say it is the same.
```
current_entry->prompt->type = P_MENU;
```
Of course, it shares a lot of code with T_CONFIG, but also it does with T_MENU/T_MAINMENU. And I don't think there is any autodetector that completely ignores T_MENUCONFIG entries, then analyses the structure to automatically group symbols into menu. "depends on" may produce complex graphs of symbols, but in kernel config we see only relevant items in any MENUCONFIG.

**Comment by ulfalizer** [comment]
Ah, you're right, that is a difference. It's only related to presentation though. So far I've focused on the evaluation logic.

I still think there's an autodetector though, because I ran into a "bug" caused by it that forced me to partially implement it. See the comments near `_determine_actual_symbols()` and `_has_auto_menu_dep_on()`. It could be that `menuconfig` was used inside those problematic `choice`s as well, but I don't think so.

**Comment by ulfalizer** [comment]
I think I found the code that implements it now. It's [this block](http://lxr.free-electrons.com/source/scripts/kconfig/menu.c#L341) inside `menu_finalize`. The following code checks the dependency on the "preceding" symbol:

    if (expr_depends_symbol(dep, sym))
        goto next;

When reading that code, it helps to know that `struct menu` represents any kind of menu *entry*. Each symbol will get a separate `struct menu` instance for example. How the `struct menu`s are connected determines the menu structure as seen in menuconfig.

**Comment by neumond** [comment]
Just FYI, kernel ships with nice Kconfig doc, Documentation/kbuild/kconfig-language.txt
I've referenced it in attempt to implement Kconfig parser, just before I decided to google :)

Description is very simple here.
```
menuconfig:
        "menuconfig" <symbol>
        <config options>

This is similar to the simple config entry above, but it also gives a
hint to front ends, that all suboptions should be displayed as a
separate list of options.
```

**Comment by ulfalizer** [comment]
Yeah, I know about that document. Just didn't remember that particular part.

Yup, a current limitation of Kconfiglib is that it doesn't have any APIs for dealing with such "cosmetic" menus. `config` is treated the same as `menuconfig`. For "real" menus, there's plenty of stuff (check the Menu class).

**Comment by ulfalizer** [comment]
Hello,

Just FYI, I just released an improved redesign of Kconfiglib with (among other things) implicit menu support and direct access to the menu structure.

There's now a menuconfig example in ``examples/menuconfig.py``. Whether or not a symbol is defined with ``menuconfig`` as opposed to ``config`` is captured in the ``MenuNode.is_menuconfig`` flag.

The example currently doesn't display ``menuconfig`` Symbol nodes any differently though, to keep things simple.

Cheers,
Ulf
