### ISSUE TITLE
Feature Request: Add to PyPi

### ISSUE THREAD

**Issue by Skrupellos** [ulfalizer/Kconfiglib#24]
Hi,

it would be pretty neat to see this lib in PyPI - the Python Package Index. This allows everyone to install it using pip, Python software to install it as a dependency and Linux distros to more easily package it.

**Comment by ulfalizer** [comment]
Hello,

Sorry for the late reply, but I felt bad about adding Kconfiglib to PyPI without `imply` support, which is required for recent kernels. Now that `imply` is supported and everything's been brought up to date, I've added Kconfiglib to PyPI!

Please tell me if you spot any problems or possible improvements re. the packaging. The README has been updated with new information.

Cheers,
Ulf
