### ISSUE TITLE
Support new 'imply' keyword

### ISSUE THREAD

**Issue by trini** [ulfalizer/Kconfiglib#26]
With the v4.10 Linux Kernel (and commit 237e3ad0f195d8fd34f1299e45f04793832a16fc) a new "imply" keyword has been added.  Quoting from the commit message:
> The "imply" keyword is a weak version of "select" where the target
> config symbol can still be turned off, avoiding those pitfalls that come
> with the "select" keyword.
>
> This is useful e.g. with multiple drivers that want to indicate their
> ability to hook into a secondary subsystem while allowing the user to
> configure that subsystem out without also having to unset these drivers.

**Comment by ulfalizer** [comment]
Hello,

Finally got around to this (fffd30e6ea060b2abebb7ba9cdf881da00ca4cb). Sorry for letting it take way too long!

Along with (35ea8d5f1d63bdc9f8642f5ce4445e8f7c914385), all tests now pass again
in obsessive test suite mode with Linus' latest tree (4.13).
