### ISSUE TITLE
defconfig example wrong?

### ISSUE THREAD

**Issue by tych0** [ulfalizer/Kconfiglib#28]
Hi,

when I try to do something similar to the defconfig example, it seems to emit config options incorrectly for me:

```
~/packages/linux (HEAD detached from v4.4.67) cat tester.py 
import sys

import kconfiglib

config = kconfiglib.Config(sys.argv[1])
config.load_config(config.get_defconfig_filename())

print(config.get_symbol("BPF_SYSCALL").get_value())
~/packages/linux (HEAD detached from v4.4.67) make scriptconfig SCRIPT=./tester.py
warning: the value "m" is invalid for BATTERY_BQ27XXX_I2C, which has type bool. Assignment ignored.
warning: the value "m" is invalid for MFD_AXP20X, which has type bool. Assignment ignored.
warning: the value "m" is invalid for WILC1000_SDIO, which has type bool. Assignment ignored.
warning: the value "m" is invalid for WILC1000_SPI, which has type bool. Assignment ignored.
y
~/packages/linux (HEAD detached from v4.4.67) make defconfig
*** Default configuration is based on 'x86_64_defconfig'
#
# configuration written to .config
#
~/packages/linux (HEAD detached from v4.4.67) grep BPF_SYSCALL .config
# CONFIG_BPF_SYSCALL is not set
```

I must be missing something, but I'm not sure what :)

**Comment by ulfalizer** [comment]
Hello!

Could you check what value is returned by `config.get_defconfig_filename()` and also do a `config.write_config("kconfiglib_config")` and compare it against .config to check if/how they differ? Kconfig semantics can get pretty tricky at times, and it'd be helpful info to have.

Thanks!

**Comment by tych0** [comment]
Huh, looks like it is pointing somewhere weird:

```
~/packages/linux (HEAD detached at b60692d) cat tester.py 
import sys

import kconfiglib

config = kconfiglib.Config(sys.argv[1])
print(config.get_defconfig_filename())
config.load_config(config.get_defconfig_filename())

print(config.get_symbol("BPF_SYSCALL").get_value())
config.write_config("kconfiglib_config")
~/packages/linux (HEAD detached at b60692d) make scriptconfig SCRIPT=./tester.py
/boot/config-4.8.0-51-generic
warning: the value "m" is invalid for BATTERY_BQ27XXX_I2C, which has type bool. Assignment ignored.
warning: the value "m" is invalid for MFD_AXP20X, which has type bool. Assignment ignored.
warning: the value "m" is invalid for WILC1000_SDIO, which has type bool. Assignment ignored.
warning: the value "m" is invalid for WILC1000_SPI, which has type bool. Assignment ignored.
```

any ideas why?

**Comment by ulfalizer** [comment]
Sorry for going MIA for a while there.

I just remembered that I ran into this as well, and added a warning to the `Config.get_defconfig_filename()` documentation:

    WARNING: A wart here is that scripts/kconfig/Makefile sometimes uses
    the --defconfig=<defconfig> option when calling the C implementation of
    e.g. 'make defconfig'. This option overrides the 'option
    defconfig_list' symbol, meaning the result from
    get_defconfig_filename() might not match what 'make defconfig' would
    use. That probably ought to be worked around somehow, so that this
    function always gives the "expected" result."""

Looking into `scripts/kconfig/Makefile`, there's the following, which confirms the suspicion:

    defconfig: $(obj)/conf
    ifeq ($(KBUILD_DEFCONFIG),)
    	$< $(silent) --defconfig $(Kconfig)
    else
    ifneq ($(wildcard $(srctree)/arch/$(SRCARCH)/configs/$(KBUILD_DEFCONFIG)),)
    	@$(kecho) "*** Default configuration is based on '$(KBUILD_DEFCONFIG)'"
    	$(Q)$< $(silent) --defconfig=arch/$(SRCARCH)/configs/$(KBUILD_DEFCONFIG) $(Kconfig)
    else
    	@$(kecho) "*** Default configuration is based on target '$(KBUILD_DEFCONFIG)'"
    	$(Q)$(MAKE) -f $(srctree)/Makefile $(KBUILD_DEFCONFIG)
    endif
    endif

The problem is that the kbuild Makefiles explicitly pass a .config to be used in the case of `make defconfig`, rather than looking at the `defconfig_list` symbol. When running `make menuconfig` instead and saving and exiting, `defconfig_list` is used, and so the same defconfig file is used by kconfig and kconfiglib in that case.

You might have to wrestle with the kbuild Makefiles a bit to get what you want. `get_defconfig_filename()` seems to work as intended at least.
