### ISSUE TITLE
Dependencies for choice symbols

### ISSUE THREAD

**Issue by olegartys** [ulfalizer/Kconfiglib#29]
Hi!

I think it will be very handful to parse dependencies not only from enclosing menus and ifs, but for choice options from their parents too. For example: 

```
choice CHOICE
        default SYMBOL1
	prompt "CHOICE"

config SYMBOL1
	default n
	bool "SYMBOL1"

config SYMBOL2
	default n
	bool "SYMBOL2"

endchoice
```

SYMBOL1 and SYMBOL2 are dependent on CHOICE, so it will be very useful to have possibility to get this dependency by the API method or just from deserializied string option info (like "Additional dependencies from enclosing menus and ifs:" section).

Is it hard feature to implement? Thank you.

**Comment by ulfalizer** [comment]
Hello,

Are you thinking of the `get_referenced_symbols()` method? Unfortunately, having that one return a list that includes the `Choice` would break backwards compatibility, especially as the `Choice` API isn't identical to the `Symbol` API.

Or do you mean having `get_referenced_symbols(refs_from_enclosing=True)` on a symbol inside a choice include all the symbols referenced by the choice? That makes intuitive sense, but might get a bit arbitrary. For example, if you're trying to figure out what symbols `SYMBOL2` is "connected" to somehow, then it seems weird to only include `SYMBOL1` if the parent choice has `default SYMBOL1`.

I think choices might be "special" enough that it's okay to have to handle them manually. You could use a helper function like the following to implement the behavior you want:

    def referenced_syms(sym):
        res = sym.get_referenced_symbols(True)
        if sym.is_choice_symbol():
            res |= sym.get_parent().get_referenced_symbols()
        return res

Cheers

**Comment by olegartys** [comment]
Thank you for great response, I understood your point.

Actually I am trying to solve the next task: I am trying to solve the next problem. I am trying to resolve all it's dependencies by recursively scanning options. Option become enabled.

I am solving the task by parsing `Symbol`'s string representation and getting all the dependent option and logical expressions, and then trying to solve them. This task is repeated for all the dependent option and then set of options with their new deemed values is injected into .config. So now for a Choice options I am using the same workaround as you suggested and if you think it is allright, I am completely agree with you. :)

Thanks for the advice, if you can propose some more convenient solution to my task using Kconfig API, I would much appreciate it.

**Comment by ulfalizer** [comment]
Accessing the expressions directly might be easier than parsing the string representation. Expressions are represented in a pretty simple way internally (see the docstring for `Config._parse_expr()`), and even though it's strictly internal stuff, it's unlikely to change at this point.

You could check out `Symbol.__init__()`, `Choice.__init__()`, and `Config._get_sym_or_choice_str()` (last one is used to build the string representation) to see what variables hold the various expressions.

You might be thinking that some API could be added that returns e.g. all the symbols that need to be enabled in order for some symbol to be visible. That makes perfect sense intuitively, but unfortunately it gets tricky to define what it means when you can have complicated expressions with `||` and the like. At this point, I just recommend looking at the internal expression representations.

**Comment by ulfalizer** [comment]
Hello,

Just FYI, I just released an improved redesign of Kconfiglib with (among other things) direct access to expressions. Choices now appear directly in the properties of choice symbols.

Cheers,
Ulf

**Comment by olegartys** [comment]
Hi,

Thank you very much for your attention!

Best regards,
Oleg
