### ISSUE TITLE
how to set a string vaule or integer for a symbol using Symbol.set_value()

### ISSUE THREAD

**Issue by Jasonjunsu** [ulfalizer/Kconfiglib#31]

**Comment by ulfalizer** [comment]
Hello,

Guessing you figured it out yourself, but for `int` and `hex` values, just pass the value as a string. Invalid values will be rejected.

The reason integers aren't accepted directly is that the format is sometimes preserved exactly as is, and Kconfiglib needs to emulate that.

By the way, please tell me if the documentation could be clearer anywhere.

Cheers,
Ulf
