### ISSUE TITLE
kernel v4.18 added new kconfig fefatures

### ISSUE THREAD

**Issue by dzickusrh** [ulfalizer/Kconfiglib#46]
Hi,

Started using this standalone library for some sanity kconfig checks for the kernel.  Noticed in v4.18 a whole bunch of new features were added that are not here yet.

For starters, scripts/Kconfig.include has new unsupported token := and then all the shell scripting stuff.
Finally the embedded use of environment variables see $(SRCARCH) in Kconfig.

There is a lot there to implement, not sure if that is something planned or not.

Thanks for this tool!

Cheers,
Don

**Comment by ulfalizer** [comment]
Hello,

Yep, it's planned. Was waiting for it to stabilize, but looks like it's in linux-next now at least.

The kernel community has some kind of NIH-induced spite against Kconfiglib and tends to actively ignore it exists (going for shoddy shell scripts and Python scripts that reinvent the wheel instead), so so far I have to play catchup whenever new stuff gets added.

Lots of things I'd want to improve if it didn't have to stay compatible.

Just slightly bitter... :P

**Comment by dzickusrh** [comment]
Thanks!  Good to know!  Though I am kinda stuck as I am working on config options for 4.18.  I was trying to hack up the tool to quickly stub out some of the new options as I don't care about a lot of it.  Having some success, but not where I want to be.  May have to fall back to the C tool for now. :-(

**Comment by ulfalizer** [comment]
I'll see if I can get started on it next week. Bit busy with unrelated work stuff, but I'm allowed to work on Kconfiglib too, so maybe if I'm lucky...

The Python version should be a lot simpler than the C version at least.

**Comment by ulfalizer** [comment]
@dzickusrh 
Got most of it done now. The kernel Kconfigs parse again, but the output is broken (predefined functions like `shell` aren't implemented yet).

If you want to, I could push the WIP I have now to a separate branch. Otherwise, everything should be done within a few days (need comprehensive tests, documentation, etc., too).

**Comment by dzickusrh** [comment]
@ulfalizer, wow thanks!  I will happily play with a WIP.  I mainly use the tool as a read-only interface to the data to help me organize new kconfig symbols as they are introduced.  As long as Kconfig() can return successfully, I am happy. :-)

**Comment by dzickusrh** [comment]
@ulfalizer Thank you!  It seems to work.  I haven't verified all the data and I still see various warnings, but it seems to be working for my needs.  Thanks!

**Comment by ulfalizer** [comment]
I've pushed out a new release that implements the preprocessor now.
