### ISSUE TITLE
Tentative request: Add themeing support to menuconfig

### ISSUE THREAD

**Issue by pinkfluid** [ulfalizer/Kconfiglib#52]
This is my last request, I promise :)

It would be nice if it was possible to change the color scheme of menuconfig. I'm not exactly sure what would be the best way to do it, but here are a couple options that come to mind:

- environment variable
- command line 
- config file
- comments in the kconfig file 

The first 3 are self explanatory. The last option, could be something like Vim modeline that allows settings things like TAB size from the Kconfig file comments, for example:

```
# $menuconfig: separator=bold_black_on_yellow,standout
# $menuconfig: frame=black_on_yellow,standout;style=black on white;...

config TEST
     bool "A"
...
```
The above color definition syntax is somewhat loosely resembling python blessings (https://github.com/erikrose/blessings). The definition after "," is the 4th column for _style().

If there's no plans for this whatsoever, please close the issue :)

**Comment by ulfalizer** [comment]
6th option might be to make the default less ugly. I did my best with it, but I'm not exactly Rembrandt. That yellow color in particular probably isn't the prettiest thing in the world...

If someone comes up with a nicer color scheme (or other UI improvement), I'm happy to take it in. Not sticking to just the predefined colors might help too.

The C menuconfig gets decent looks from using [lxdialog](https://en.wikipedia.org/wiki/Dialog_(software)), but I don't like how it wastes terminal space, and resizing is super janky (including a segfault if you accidentally make the window too small).

**Comment by pinkfluid** [comment]
I don't think it's ugly, actually it's pretty decent even for Rembrandt standards.

The problem is that when I present this to other people they expect the ctools "kconfig" theme. So I was hoping to customize it with colors that are more in-line with the project so instead of a "uh, huh... why is it yellow?" questions I would get more "Oh, cool" reactions :)

It's not super important, so if you think it's pointless to have, please close the issue.

**Comment by ulfalizer** [comment]
I tried to go for the `make menuconfig` colors at first, but iirc I ran into color clashes due to the more compact layout.

Could you try tweaking the colors manually in `_init_styles()` and seeing if you can come up with something more `make menuconfig`-like that looks nice? Once we know that it's possible, I could try to come up with some theming thing.

**Comment by ulfalizer** [comment]
Search for "predefined" in https://docs.python.org/3/library/curses.html to see the list of predefined colors.

Might be able to use `curses.init_color()` to get custom colors, though it's terminal-dependent (should check `curses.can_change_color()` in that case too).

**Comment by pinkfluid** [comment]
I will give it a shot.

I thought init_color() was only for RGB-type colors (some terminals do support that). I might try with the standard 16 colors at first, see how far I get.

**Comment by pinkfluid** [comment]
Ok, this is what I came up with. Frankly, it looks more like Norton Commander than lxdialog :)

As you said, it's really hard to match the lxdialog scheme because of the borders and all that.

Anyway, here's the patch:
```
diff --git a/menuconfig.py b/menuconfig.py
index 2166787..266578e 100755
--- a/menuconfig.py
+++ b/menuconfig.py
@@ -184,7 +184,7 @@ def _init_styles():
 
     # Separator lines between windows. Also used for the top line in the symbol
     # information dialog.
-    _SEPARATOR_STYLE          = _style(curses.COLOR_BLACK, curses.COLOR_YELLOW, BOLD,            curses.A_STANDOUT)
+    _SEPARATOR_STYLE          = _style(curses.COLOR_WHITE, curses.COLOR_CYAN,   BOLD,            curses.A_STANDOUT)
 
     # Edit boxes
     _INPUT_FIELD_STYLE        = _style(curses.COLOR_WHITE, curses.COLOR_BLUE,   curses.A_NORMAL, curses.A_STANDOUT)
@@ -192,25 +192,25 @@ def _init_styles():
     # List of items, e.g. the main display
     _LIST_STYLE               = _style(curses.COLOR_BLACK, curses.COLOR_WHITE,  curses.A_NORMAL                   )
     # Style for the selected item
-    _LIST_SEL_STYLE           = _style(curses.COLOR_WHITE, curses.COLOR_BLUE,   curses.A_NORMAL, curses.A_STANDOUT)
+    _LIST_SEL_STYLE           = _style(curses.COLOR_WHITE, curses.COLOR_BLUE,   BOLD           , curses.A_STANDOUT)
 
     # Like _LIST_(SEL_)STYLE, for invisible items. Used in show-all mode.
     _LIST_INVISIBLE_STYLE     = _style(curses.COLOR_RED,   curses.COLOR_WHITE,  curses.A_NORMAL, BOLD             )
     _LIST_INVISIBLE_SEL_STYLE = _style(curses.COLOR_RED,   curses.COLOR_BLUE,   curses.A_NORMAL, curses.A_STANDOUT)
 
     # Help text windows at the bottom of various fullscreen dialogs
-    _HELP_STYLE               = _style(curses.COLOR_BLACK, curses.COLOR_WHITE,  BOLD                              )
+    _HELP_STYLE               = _style(curses.COLOR_CYAN, curses.COLOR_BLUE,    BOLD                              )
 
     # Top row in the main display, with the menu path
-    _PATH_STYLE               = _style(curses.COLOR_BLACK, curses.COLOR_WHITE,  BOLD                              )
+    _PATH_STYLE               = _style(curses.COLOR_CYAN, curses.COLOR_BLUE,    BOLD                              )
 
     # Symbol information text
     _INFO_TEXT_STYLE          = _LIST_STYLE
 
     # Frame around dialog boxes
-    _DIALOG_FRAME_STYLE       = _style(curses.COLOR_BLACK, curses.COLOR_YELLOW, BOLD,            curses.A_STANDOUT)
+    _DIALOG_FRAME_STYLE       = _style(curses.COLOR_WHITE, curses.COLOR_CYAN,   BOLD,            curses.A_STANDOUT)
     # Body of dialog boxes
-    _DIALOG_BODY_STYLE        = _style(curses.COLOR_WHITE, curses.COLOR_BLACK,  curses.A_NORMAL                   )
+    _DIALOG_BODY_STYLE        = _style(curses.COLOR_CYAN, curses.COLOR_BLUE,    BOLD                              )
 
 
 #
```

And a screenshot:
![2018-08-27-201431_562x362_scrot](https://user-images.githubusercontent.com/1593069/44677319-ec585280-aa35-11e8-9dc6-6a073f5418f4.png)

**Comment by ulfalizer** [comment]
Doesn't look all too shabby. Bit more relaxed to compared to the other theme.

Maybe I could add it as an alternate theme, enabled in the environment via `MENUCONFIG_THEME=aquatic` or the like. I'm a bit scared of adding a fine-grained styling mechanism, in case I later decide to make significant changes to the interface (no such plans at the moment, but you never know).

I like that you bolded the selected item. Might steal that for the other theme as well.

Here's how it comes out on gnome-terminal:

![skarmbild fran 2018-08-27 22-25-56](https://user-images.githubusercontent.com/154768/44684455-6c3be800-aa49-11e8-93ce-5482f0eabc88.png)

**Comment by ulfalizer** [comment]
Added the new theme: https://github.com/ulfalizer/Kconfiglib/commit/84bd8634bb5de0895ff3354c394f43b923acb230

I tweaked the colors for dialog boxes and the jump-to dialog to make them a bit more readable. Check if looks alright.

Got lazy and went for a hardcoded version for now. Might add some external styling mechanism later, if more styles show up.

**Comment by mitja-plume** [comment]
Looks great, thank you!

I think we can close this issue.

**Comment by pinkfluid** [comment]
Looks great, thank you!

You can close this issue.

**Comment by ulfalizer** [comment]
Alright, closing. Thanks!

Pushed out a new release with the theme too.
