### ISSUE TITLE
Duplicate rsource

### ISSUE THREAD

**Issue by oyvindronningstad** [ulfalizer/Kconfiglib#60]
Say you have two files

    #foo.Kconfig
    config FOO
        bool "Foo"
    if FOO
        rsource bar.Kconfig
    endif
    if !FOO
        rsource bar.Kconfig
    endif

and

    #bar.Kconfig
    choice BAR
        prompt "BAR"
        config BAR1
            bool "BAR1"
        config BAR2
            bool "BAR2"
    endchoice

No matter if FOO is `y` or `n`, the BAR menu looks like this

    (X) BAR1
    ( ) BAR2
    (X) BAR1
    ( ) BAR2

And if I choose a BAR2

    ( ) BAR1
    (X) BAR2
    ( ) BAR1
    (X) BAR2

This might seem contrived, but sometimes it's useful to be able to present a menu one place in one context and in another place in another context.

I don't know if this affects other `source` commands as well.

**Comment by ulfalizer** [comment]
This is a side effect of a choice-specific hack that was added to the menuconfig in commit 17d7c1e ("menuconfig: Show all symbols at each menu location for multi.def. choices"). People requested to be able to add symbols to choices by defining them in multiple locations, so I put that in.

In this case, multiple menu nodes for the same symbol get added though, which looks weird. I should probably filter out duplicates.

I'll see if I can cook something up. It's not a bug at least, just a case that turns a bit wonky. :)

**Comment by ulfalizer** [comment]
There is a simpler thing you can do here by the way, thanks to that hack:

```
config FOO
    bool "Foo"

if FOO

choice BAR
    prompt "BAR"

config BAR1
    bool "BAR1"

config BAR2
    bool "BAR2"

endchoice

endif

if !FOO

choice BAR
    prompt "BAR 2"
endchoice

endif
```

That just adds a second definition location for the choice, and if you enter it via that definition location, you'll still be able to see all the symbols.

**Comment by oyvindronningstad** [comment]
It's more evident in the following case. (foo.Kconfig is unchanged)

    #bar.Kconfig
    menu BARMENU
    config BAZ
        bool "BAZ"
    choice BAR
        prompt "BAR"
        config BAR1
            bool "BAR1"
        config BAR2
            bool "BAR2"
    endchoice
    endmenu

BARMENU and BAZ render as expected, but the choices are still duplicated.

**Comment by ulfalizer** [comment]
@oyvindronningstad 
Try just having

```
choice BAR
    prompt "Whatever"
endchoice
```

wherever you want the second menu entry for the choice to appear.

The choice symbols themselves only depend on the choice, and defining a symbol/choice in multiple locations makes the direct dependencies the `OR` of the dependencies at each location, so it should work out dependency-wise.

**Comment by oyvindronningstad** [comment]
The thing is I want the complete BARMENU in two different places, but only one at a time. This works fine if I use `if`s right, except for the fact that all choice entries are duplicated. I don't think the hack should be active for this since only one choice definition is actually active (the other is behind an inactive `if`)

**Comment by ulfalizer** [comment]
Ah... I see what you mean now. Yeah, if you want to copy-paste whole menus in different places, it gets trickier.

The choice hack works at the menu node level (you get n menu nodes if you define a symbol/choice in n locations, all pointing to the same symbol/choice), because it's needed to support some weird stuff that people sometimes do with choices. If required, I could add a filter so that only one menu node is kept if you get multiple menu nodes in the choice pointing to the same symbol though.

Just be careful so that you don't create something that's super hard for Kconfig beginners to understand. :)

**Comment by oyvindronningstad** [comment]
I must admit I don't understand all the details, but to me it's obvious that

    if FOO
        rsource bar.Kconfig
    endif

Should completely omit anything inside the `if` if FOO is n. Likewise,

    if !FOO
        rsource bar.Kconfig
    endif

Should completely omit anything inside the `if` if FOO is y.

So there should be no reason anything is duplicated.

I think I understand the purpose of the hack. It's so

    choice CHOICE
        config CHOICE1
        config CHOICE2
    endchoice

can also be written like this

    choice CHOICE
        config CHOICE1
    endchoice
    ...
    choice CHOICE
        config CHOICE2
    endchoice

right?

Well, the problem is that

    config FOO
        bool "Foo"
    if FOO
        choice BAR
            prompt "BAR"
            config BAR1
                bool "BAR1"
        endchoice
    endif
    if !FOO
        choice BAR
            prompt "BAR"
            config BAR2
                bool "BAR2"
        endchoice
    endif

Behaves as if there are no `if`s, which I find very odd.

**Comment by oyvindronningstad** [comment]
Ok, I think I see. Kconfig `if`s more dependency-declarations than they are regular `if`s.

Anyway, I guess duplicate choice symbols don't really make sense, so can you strip duplicates from the list? :)

**Comment by ulfalizer** [comment]
Yeah, `if`s are just a shorthand for adding `depends on` to all items within the `if`. An `if FOO` can appear before `FOO` (or something `FOO` depends on) is even defined.

Could you try this patch and see if it gives the behavior you expect? The choice selection is displayed duplicated, for obscure reasons (it's intentional, but looks weird), but I could work around that later if needed.

```diff
diff --git a/menuconfig.py b/menuconfig.py
index 88c3429..39e9227 100755
--- a/menuconfig.py
+++ b/menuconfig.py
@@ -1421,9 +1421,13 @@ def _shown_nodes(menu):
         #
         # Note: Named choices are pretty broken in the C tools, and this is
         # super obscure, so you probably won't find much that relies on this.
-        return [node
-                for choice_node in menu.item.nodes
-                    for node in rec(choice_node.list)]
+        added = set()
+        res = []
+        for choice_node in menu.item.nodes:
+            for node in rec(choice_node.list):
+                if isinstance(node.item, Symbol) and node.item not in added:
+                    res.append(node)
+                    added.add(node.item)
 
     return rec(menu.list)
```

**Comment by oyvindronningstad** [comment]
> Could you try this patch and see if it gives the behavior you expect?

It works :)

**Comment by ulfalizer** [comment]
Alright, I'll see if I can hack something up based on that. Bit sad to see the hack grow though. :/

Try to see if you can avoid the multiple-definition stuff too. Kconfig is usually pretty straightforward and intuitive as long as people don't go all-in on that stuff. Starting to sound like someone's mom though. :P

**Comment by ulfalizer** [comment]
Changed the behavior in commit b3f0061 ("menuconfig: Only list duplicated choice symbols once"). I'll prepare a commit for Zephyr as well.
