### ISSUE TITLE
Doesn't support help in the menuconfig.

### ISSUE THREAD

**Issue by swordligit** [ulfalizer/Kconfiglib#62]
Very useful work for making a cross platform menuconfig.Thanks.
A little issue, when press 'h' key in the menuconfig dialog, there is no help window pop up.
Do you have plan to add this feature?

**Comment by ulfalizer** [comment]
Which menuconfig are you talking about?

In the terminal menuconfig, you can press `?` to view the help text and other info for a menu entry. Pressing `F` will toggle the window at the bottom to always show the help as well.

**Comment by ulfalizer** [comment]
Ah, apparently `mconf` (`make menuconfig`) supports `h` as an alias for `?`. Had never noticed that before.

Just press `?` instead. `h` is already used for the Vi-like keybindings.

**Comment by swordligit** [comment]
Yes, this works, thanks a lot!
