### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Kconfig'

### ISSUE THREAD

**Issue by teto** [ulfalizer/Kconfiglib#66]
I wonder if argparse could not be used to pass some parameters (at least for the already restricted python3).
right now when I try to run executable, I mostly get:
`FileNotFoundError: [Errno 2] No such file or directory: 'Kconfig'`

And the 2nd step of the getting started was not helpful for me, as I wanted to analyze the kernel's config
```
1.Install the library and the utilities. Use pip3 if you want to use the terminal menuconfig.

2. Write Kconfig files that describe the available configuration options.
```
Looking further in the documentation, I saw that I could set $srctree (I had KCONFIG_CONFIG already set) which I did but now I have:
```
Traceback (most recent call last):
  File "./genconfig.py", line 89, in <module>
    main()
  File "./genconfig.py", line 77, in main
    kconf = kconfiglib.Kconfig(args.kconfig_filename)
  File "/home/teto/Kconfiglib/kconfiglib.py", line 973, in __init__
    self._parse_block(None, self.top_node, self.top_node)
  File "/home/teto/Kconfiglib/kconfiglib.py", line 2647, in _parse_block
    prev = self._parse_block(None, parent, prev)
  File "/home/teto/Kconfiglib/kconfiglib.py", line 2647, in _parse_block
    prev = self._parse_block(None, parent, prev)
  File "/home/teto/Kconfiglib/kconfiglib.py", line 2645, in _parse_block
    os.path.relpath(filename, self.srctree))
  File "/home/teto/Kconfiglib/kconfiglib.py", line 1880, in _enter_file
    for name, linenr in self._include_path)))
kconfiglib.KconfigError: 
arch/Kconfig:10: Recursive 'source' of 'arch/Kconfig' detected. Check that environment variables are set correctly.
Include path:
Kconfig:12
init/Kconfig:1756
arch/Kconfig:10
```

I want to use Kconfiglib to be able to find the dependencies of a specific setting and enable them automatically. Like enabling VIRTIO_NET should enable VIRTIO, right now I do it manually. Is this something I could do with kconfiglib ? (or any other way ?)

**Comment by ulfalizer** [comment]
> I wonder if argparse could not be used to pass some parameters (at least for the already restricted python3).
> right now when I try to run executable, I mostly get:
> `FileNotFoundError: [Errno 2] No such file or directory: 'Kconfig'`

I wonder if `argparse` would really help there. The path defaults to `Kconfig` when no path is passed, and that error is from failing to open `Kconfig`. It's more an I/O error than a usage error.

`argparse`'ifying some of the utilities might be nice though, e.g. to add help texts. One thing I like about the utilities now is that they're super simple to read and understand at least.

> And the 2nd step of the getting started was not helpful for me, as I wanted to analyze the kernel's config
> 
> ```
> 1.Install the library and the utilities. Use pip3 if you want to use the terminal menuconfig.
> 
> 2. Write Kconfig files that describe the available configuration options.
> ```

Yeah, that short getting started guide assumes that you want to use Kconfiglib as a general Kconfig replacement. Maybe the library documentation could be linked from there as well.

> Looking further in the documentation, I saw that I could set $srctree (I had KCONFIG_CONFIG already set) which I did but now I have:
> 
> ```
> Traceback (most recent call last):
>   File "./genconfig.py", line 89, in <module>
>     main()
>   File "./genconfig.py", line 77, in main
>     kconf = kconfiglib.Kconfig(args.kconfig_filename)
>   File "/home/teto/Kconfiglib/kconfiglib.py", line 973, in __init__
>     self._parse_block(None, self.top_node, self.top_node)
>   File "/home/teto/Kconfiglib/kconfiglib.py", line 2647, in _parse_block
>     prev = self._parse_block(None, parent, prev)
>   File "/home/teto/Kconfiglib/kconfiglib.py", line 2647, in _parse_block
>     prev = self._parse_block(None, parent, prev)
>   File "/home/teto/Kconfiglib/kconfiglib.py", line 2645, in _parse_block
>     os.path.relpath(filename, self.srctree))
>   File "/home/teto/Kconfiglib/kconfiglib.py", line 1880, in _enter_file
>     for name, linenr in self._include_path)))
> kconfiglib.KconfigError: 
> arch/Kconfig:10: Recursive 'source' of 'arch/Kconfig' detected. Check that environment variables are set correctly.
> Include path:
> Kconfig:12
> init/Kconfig:1756
> arch/Kconfig:10
> ```

Have you read https://github.com/ulfalizer/kconfiglib#installation-for-the-linux-kernel? There are other environment variables that need to be set as well.

> I want to use Kconfiglib to be able to find the dependencies of a specific setting and enable them automatically. Like enabling VIRTIO_NET should enable VIRTIO, right now I do it manually. Is this something I could do with kconfiglib ? (or any other way ?)

This is a common thing to do. Unfortunately, it's much trickier than it might seem.

Say a symbol has direct dependencies like `(FOO || !BAR) && (BAZ = "hmm" || QAZ > 7)` for example. There are several ways that can be satisfied, and even coming up with a single way automatically might not be trivial.

It might be possible to come up with some heuristic that works for most cases , but something perfectly general is probably impossible, and would involve guessing what the user wants when e.g. `||` is involved.

**Comment by teto** [comment]
thanks for the help. I've since found in kconfig's help references towards sat solver to accomplish what I proposed. A shame there is no up to date project that does it.
