### ISSUE TITLE
Documentation for kconfig_filenames is misleading

### ISSUE THREAD

**Issue by SebastianBoe** [ulfalizer/Kconfiglib#67]
The documentation for kconfig_filenames states that:

>       A list with the filenames of all Kconfig files included in the
>       configuration, relative to $srctree (or relative to the current directory
>       if $srctree isn't set).
> 

which lead me to believe that all paths were relative to srctree, e.g. that some kind of path conversion was done for absolute paths. But in fact 'kconfig_filenames' contains both absolute paths and paths relative to srctree.

**Comment by ulfalizer** [comment]
Is this better?

```diff
diff --git a/kconfiglib.py b/kconfiglib.py
index f1d514e..771f8a1 100644
--- a/kconfiglib.py
+++ b/kconfiglib.py
@@ -609,7 +609,8 @@ class Kconfig(object):
     kconfig_filenames:
       A list with the filenames of all Kconfig files included in the
       configuration, relative to $srctree (or relative to the current directory
-      if $srctree isn't set).
+      if $srctree isn't set), except absolute paths (e.g.
+      'source "/foo/Kconfig") are kept as-is.
 
       The files are listed in the order they are source'd, starting with the
       top-level Kconfig file. If a file is source'd multiple times, it will
```

**Comment by SebastianBoe** [comment]
Looks great :)

**Comment by ulfalizer** [comment]
Zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/13586
