### ISSUE TITLE
A symbol is missing in inherited dependencies

### ISSUE THREAD

**Issue by xairy** [ulfalizer/Kconfiglib#69]
Hi,

The documentation for the `referenced` field of the `Symbol` class says that it `includes dependencies inherited from surrounding menus and if's.`. However when I look at the value of the `referenced` field for `COMEDI_NI_USB6501` ([source](https://github.com/torvalds/linux/blob/master/drivers/staging/comedi/Kconfig)), I don't see the `USB` symbol there:

``` python
> print(kconf.syms['COMEDI_NI_USB6501'].referenced)
set([<symbol COMEDI_USB_DRIVERS, tristate, "Comedi USB drivers", value m, user value m, visibility m, direct deps m, drivers/staging/comedi/Kconfig:1183>, <symbol COMEDI, tristate, "Data acquisition support (comedi)", value m, user value m, visibility y, direct deps y, drivers/staging/comedi/Kconfig:1>, <symbol STAGING, bool, "Staging drivers", value y, user value y, visibility y, direct deps y, drivers/staging/Kconfig:1>])
```

`COMEDI_NI_USB6501` depends on `COMEDI_USB_DRIVERS` through an `if`, and `COMEDI_USB_DRIVERS` in turns depends on `USB` through a `depends on`. So AFAIU `USB` should be in `referenced`.

Is this a bug or there's something I misunderstand? 

Thanks!

**Comment by ulfalizer** [comment]
Hello,

`referenced` isn't transitive. It only includes "direct" references.

The reason dependencies from surrounding `if`s and `menu`s count as direct references has to do with dependency propagation. Basically, `if FOO` is just a shorthand for adding `depends on FOO` to each item within the `if`, and a `depends on` on a menu also gets propagated to all the items in it.

These two ways of defining two symbols `A` and `B` are equivalent:

*With `if`:*

```
if B

config A
	bool

endif

if C

config B
	bool

endif
```

*With `depends on`:*

```
config A
	bool
	depends on B

config B
	bool
	depends on C
```

In both cases, `A` ends with just `B` in `referenced`, and `B` ends up with just `C`.

To get transitive references, you'll have to calculate the transitive closure (I think that's the term...), recursively expanding the `.referenced` until no new symbols appear.

If you're only interested in the direct dependencies of a symbol (it's `depends on`, possibly inherited), have a look at `Symbol.direct_dep` btw. You can extract all the symbols in it with the global `expr_items()` function.

**Comment by xairy** [comment]
Ah, OK, I see. Maybe it makes sense to mention this in the documentation? The word `inherited` seems confusing to me here. Thanks!

**Comment by ulfalizer** [comment]
Clarified the docstring and added some more details in https://github.com/ulfalizer/Kconfiglib/commit/814e2decd190d78b588dd775c1531dacd6bc38c6. Does it look okay?

**Comment by xairy** [comment]
Looks good, thanks you!
