### ISSUE TITLE
permit PYTHONCMD=ipython

### ISSUE THREAD

**Issue by dubiousjim** [ulfalizer/Kconfiglib#7]
Just stumbled on this library and am starting to explore; looks nice! One thing is, if you changed the patch to scripts/kconfig/Makefile so that it read like this, then users could use iscriptconfig with PYTHONCMD=ipython (or ipython2). 

iscriptconfig:
           ...  
           c = kconfiglib.Config(sys.argv[4 if \"$(PYTHONCMD)\".startswith(\"ipython
\") else 1]); \  
           ...

**Comment by ulfalizer** [comment]
Did you write any scripts that I could use as examples by the way?
