### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by Neutree** [ulfalizer/Kconfiglib#74]
Maybe it's better to add a .gitignore file to ignore python build files such as `*.pyc`,  when I use this repo as submodule([here](https://github.com/sipeed/MaixPy/tree/master/tools/kconfig)), it always come up with some "changes"
![image](https://user-images.githubusercontent.com/8625829/62282482-3d609a00-b482-11e9-8c4a-cab0d04095b0.png)
![image](https://user-images.githubusercontent.com/8625829/62282612-6da83880-b482-11e9-976b-26e59b207c94.png)

**Comment by ulfalizer** [comment]
Might be nice. Wonder what other files should go in there. Just irks me a little bit is that it adds another file to the top level.

I've always run Git with `git config status.showUntrackedFiles no`, so I often forget that that message exists. Configuring that for the submodule might be another option, though I don't know if it can be done in a persistent way, from the main repo.

**Comment by Neutree** [comment]
But all the developer in the team will encounter this issue,  I think it's better to ignore them in code but not in git configuration in team development. 

And `git config status.showUntrackedFiles no` is not working for vscode but good for terminal

![image](https://user-images.githubusercontent.com/8625829/62338411-05ea0000-b50b-11e9-8e1c-ca3aea041155.png)


Or I can just use `pip` to install instead of submodule~~ And it seems better
So just use the way you prefer, feel free to close this issue, thanks~

**Comment by ulfalizer** [comment]
@Neutree 
I'll just put it in a `.gitignore` file. Think I take the minimalism thing a bit far sometimes...

**Comment by ulfalizer** [comment]
Added a `.gitignore` that just ignores `*.pyc`. Tell me if you run into any other generated files that ought to be ignored.

**Comment by Neutree** [comment]
seems just pyc is enough for your repo.

and all the build files from python as bellow:
```
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# PyInstaller
#  Usually these files are written by a python script from a template
#  before PyInstaller builds the exe, so as to inject date/other infos into it.
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
.hypothesis/
.pytest_cache/

# Translations
*.mo
*.pot

# Django stuff:
*.log
local_settings.py
db.sqlite3

# Flask stuff:
instance/
.webassets-cache

# Scrapy stuff:
.scrapy

# Sphinx documentation
docs/_build/

# PyBuilder
target/

# Jupyter Notebook
.ipynb_checkpoints

# pyenv
.python-version

# celery beat schedule file
celerybeat-schedule

# SageMath parsed files
*.sage.py

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Spyder project settings
.spyderproject
.spyproject

# Rope project settings
.ropeproject

# mkdocs documentation
/site

# mypy
.mypy_cache/
```

**Comment by ulfalizer** [comment]
Yeah, was looking at https://github.com/github/gitignore/blob/master/Python.gitignore for inspiration, but I think most of those might be a bit overkill or not apply for this project.
