### ISSUE TITLE
need a new interface "get_depends_on_symbols"

### ISSUE THREAD

**Issue by fpemud** [ulfalizer/Kconfiglib#8]
Hi, I'm continuing my project fpemud-kernelmanager.

Now, I need to get the menuconfig structure, eg:
```
[fpemud-workstation]# cat /usr/src/linux/fs/ext2/Kconfig
config EXT2_FS
	tristate "Second extended fs support"
	  ...
config EXT2_FS_XATTR
	bool "Ext2 extended attributes"
	depends on EXT2_FS
	  ...
config EXT2_FS_POSIX_ACL
	bool "Ext2 POSIX Access Control Lists"
	depends on EXT2_FS_XATTR
	  ...
config EXT2_FS_SECURITY
	bool "Ext2 Security Labels"
	depends on EXT2_FS_XATTR
	  ...
config EXT2_FS_XIP
	bool "Ext2 execute in place support"
	depends on EXT2_FS && MMU
	  ...
```
The corresponding menu structure is:
```
<M> Second extended fs support
[*]   Ext2 extended attributes
[*]     Ext2 POSIX Access Control Lists
[*]     Ext2 Security Labels
[*]   Ext2 execute in place support
```

I think I can get the this info by "depends on" expression: symbol is a child if it depends on another symbol above.
Currently, there's only "get_referenced_symbols" & "get_selected_symbols" interface, maybe we should add a new interface "get_depends_on_symbols"?

What do you think? I'm reading the relevant code, any hint on how to implement?

**Comment by ulfalizer** [comment]
Just FYI, I just released an improved redesign of Kconfiglib 2 with implicit menu support. It also exports all the expressions directly, avoiding the need for specialized accessors.
