### ISSUE TITLE
Autoheader header not decoded properly from environmental variable

### ISSUE THREAD

**Issue by leandrolanzieri** [ulfalizer/Kconfiglib#81]
de45874719772a40f1d8d244e2f5a6c6036415ac introduced the feature to pass a header string for the autoheader file via the environmental variable `KCONFIG_AUTOHEADER_HEADER`. The problem I found is that when this environmental variable is set by an `export` command or a Makefile for example (not in python via `os.environ[...]`), the string is not decoded properly and the `\n` is inserted in the header.

### Steps to reproduce
- Set the environmental variable: `export KCONFIG_AUTOHEADER_HEADER="/* My Header */\n"`
- Generate an autoheader using `genconfig.py`
- The expected result would be to have:
```C
/* My Header */
CONFIG_....
```
- What I get:
```C
/* My Header */\nCONFIG_...
```
---
Decoding the variable helped fixing this:
```python
self.header_header = os.getenv("KCONFIG_AUTOHEADER_HEADER", "").decode("unicode_escape")
```
Although I'm not sure this is really portable to Python3.

**Comment by ulfalizer** [comment]
Can do this if you want to put a newline into an environment variable:

```
export FOO="first line
second line"
```

If you want it on a single line, this will work (in Bash at least):

```
export FOO=$(echo -e 'first line\nsecond line')
```

`-e` is to enable interpretation of escape sequences.

Bit afraid that decoding it might lead to unintended side effects. Simpler to use the value "as is", though it has some gotchas.

**Comment by ulfalizer** [comment]
https://stackoverflow.com/questions/9139401/trying-to-embed-newline-in-a-variable-in-bash  has some tips too. Had forgotten about that `$'\n'` thing in Bash/ZSH.

**Comment by ulfalizer** [comment]
If you're using `make`, then this might be handy: https://stackoverflow.com/questions/649246/is-it-possible-to-create-a-multi-line-string-variable-in-a-makefile

**Comment by leandrolanzieri** [comment]
> If you're using `make`, then this might be handy: https://stackoverflow.com/questions/649246/is-it-possible-to-create-a-multi-line-string-variable-in-a-makefile

Thanks for this.

> Bit afraid that decoding it might lead to unintended side effects. Simpler to use the value "as is", though it has some gotchas.

Fair enough, closing this then.
