### ISSUE TITLE
Can you add support for `menuconfig`

### ISSUE THREAD

**Issue by xelll** [ulfalizer/Kconfiglib#83]
hi, Kconfiglib is a awsome project, i really like it.
but i see it is not support menuconfig now,can you add  it?

![image](https://user-images.githubusercontent.com/13636938/71456094-c92ce700-27d2-11ea-8108-6775fdd8065e.png)
![image](https://user-images.githubusercontent.com/13636938/71456111-dfd33e00-27d2-11ea-8403-aead7631005f.png)

**Comment by ulfalizer** [comment]
There's a `menuconfig`, and also a graphical `guiconfig` interface.

See [this part of the README](https://github.com/ulfalizer/Kconfiglib#menuconfig-interfaces). The code is in `menuconfig.py` and `guiconfig.py`. If you install Kconfiglib via `pip`, the executables are called `menuconfig` and `guiconfig`.

**Comment by ulfalizer** [comment]
Closing since there is a `menuconfig` already.

Might have to add it to the project you're using Kconfiglib with if it's missing there.

Cheers.

**Comment by Neutree** [comment]
What @xelll  want  is not the `menuconfig` command which already exist, but the `menuconfig keyword` in `Kconfig` file, like Openwrt did just like the screenshot above.

If we enable this item a `expand symbol ( ---> )`will show up, and we can config the items in the `menuconfig` item, 
so I think actually `menuconfig` = `menu` + `bool config item`,  just the UI's difference for user ([kbuild doc](https://www.kernel.org/doc/Documentation/kbuild/kconfig-language.txt)), so it's a new feature request~

Kconfig content maybe like this:

```
menuconfig ENABLE_COMPONENT1
    bool "enable component1"
    default n

     config COMPONENT1_CONF1
        bool "...."
        defaul y
     .
     .
     .

```

we can use this Kconfig instead now:

```
config ENABLE_COMPONENT1
    bool "enbale component 1"
   default n

menu "component1 config"
     config COMPONENT1_CONF1
        depends on ENABLE_COMPONENT1
        bool "...."
        defaul y

endmenu

```

**Comment by ulfalizer** [comment]
The `menuconfig` keyword is supported as well, and is respected by `menuconfig`. Are you running into any problems with it?

[Here's some documentation](https://docs.zephyrproject.org/latest/guides/kconfig/tips.html#menuconfig-symbols) I wrote for it by the way.
